name: bang
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  collection: ^1.18.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  get_it: ^7.7.0
  auto_route: ^9.2.1+1
  gap: ^3.0.1
  local_network_room:
    path: local_network_room
  freezed_annotation: ^2.4.4
  rxdart: ^0.28.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
