name: local_network_room
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  network_info_plus: ^6.0.0
  dart_ping_ios: ^4.0.2
  dart_ping: ^9.0.1
  get_it: ^7.7.0
  rxdart: ^0.28.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  generate: true
